### ISSUE TITLE
[BUG] cpu usage keeps increasing until crash

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-dinkum-listener#98]
when using any audio transformer plugin the cpu usage will continuously increase

replicated with ggwave and fasterwhisper lang detect plugins

reported by @builderjer  and verified by @goldyfruit

**Comment by goldyfruit** [comment]
`ovos-dinkun-listener` never really crashes, process still up and "running" but there is no wakeword detection.

**Comment by JarbasAl** [comment]
please test with https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/234

i havent diagnosed the error, but both me an @mikejgray reached the conclusion it must be on that code, so maybe its fixed by the general improvements in that PR

**Comment by builderjer** [comment]
Where I noticed the bug the first time was when testing ovos-transformer-plugin-ggwave.  When it was enabled and automatically started, CPU usage would continually rise.  First indications were at about 5 minutes.  By 15 minutes, CPU was at 100 and OVOS was unusable.

Testing now, with https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/234 , it seems to have fixed the problem.  I have had ggwave transformer running for 45 minutes and no CPU increase.

**Comment by builderjer** [comment]
This is not fixed.  After a full day of being activated, my device crashed and it has to do with `ovos-ggwave-listener`.  CPU usage still rises, just not near as fast.

**Comment by JarbasAl** [comment]
can you replicate with the faster whisper lang detect? just to be sure it isnt a different issue with ggwave plugin itself

```
  "listener": {
    "audio_transformers": {
        "ovos-audio-transformer-plugin-fasterwhisper": {
            "model": "small"
        }
    }
  }
  ```

**Comment by builderjer** [comment]
Going to close this and open in ovos-audio-transformer-plugin-ggwave.

With the  above configuration, I have had no issues for over 24 hrs
